import { useState } from 'react';
import { X, Settings, Loader2, FileText } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import tugmaLogo from '../assets/tugma_logo_white.png';

interface ExportPdfModalProps {
    isOpen: boolean;
    onClose: () => void;
    columns: string[];
    rows: any[][];
    reportTitle: string;
    fileName: string;
    adminName: string;
    isSuperAdmin: boolean;
    filterText: string;
    onSuccess?: () => void;
}

export default function ExportPdfModal({
    isOpen,
    onClose,
    columns,
    rows,
    reportTitle,
    fileName,
    adminName,
    isSuperAdmin,
    filterText,
    onSuccess
}: ExportPdfModalProps) {
    const [pdfOrientation, setPdfOrientation] = useState<'portrait' | 'landscape'>('landscape');
    const [pdfSize, setPdfSize] = useState<'a4' | 'letter' | 'legal'>('a4');
    const [pdfLogo, setPdfLogo] = useState(true);
    const [pdfHeaderMode, setPdfHeaderMode] = useState<'all' | 'first'>('all');
    const [pdfPageNumbers, setPdfPageNumbers] = useState(true);
    const [isExporting, setIsExporting] = useState(false);

    const handleGeneratePDF = async () => {
        setIsExporting(true);

        try {
            const doc = new jsPDF(pdfOrientation, 'mm', pdfSize);
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();

            let imgData: HTMLImageElement | null = null;

            if (pdfLogo) {
                imgData = new Image();
                imgData.src = tugmaLogo;
                await new Promise((resolve) => {
                    imgData!.onload = resolve;
                    imgData!.onerror = resolve; 
                });
            }
            const startYPosition = 55;

            autoTable(doc, {
                head: [columns],
                body: rows,
                startY: startYPosition,
                margin: { top: pdfHeaderMode === 'all' ? 55 : 15, bottom: 20, left: 14, right: 14 },
                styles: { fontSize: 8, cellPadding: 3 },
                headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: 'bold' },
                alternateRowStyles: { fillColor: [245, 245, 245] },
                didDrawPage: (data) => {

                    if (pdfHeaderMode === 'all' || data.pageNumber === 1) {

                        // Background Header
                        doc.setFillColor(15, 9, 30); 
                        doc.rect(0, 0, pageWidth, 35, 'F');

                        // Logo
                        let textStartX = 14;
                        if (pdfLogo && imgData) {
                            try { doc.addImage(imgData, 'PNG', 14, 5, 28, 24); } catch (e) { }
                            textStartX = 48; // Push text to the right of the logo
                        }

                        // Title
                        doc.setFontSize(22);
                        doc.setTextColor(255, 255, 255);
                        doc.setFont('helvetica', 'bold');
                        doc.text(reportTitle, textStartX, 16);

                        // Generator Details
                        const roleTag = isSuperAdmin ? 'SUPER ADMIN' : 'ADMIN';

                        doc.setFontSize(10);
                        doc.setFont('helvetica', 'normal');
                        doc.setTextColor(180, 180, 180);
                        doc.text(`Generated by: ${adminName} (${roleTag})`, textStartX, 24);

                        doc.text(`Report Date: ${new Date().toLocaleString()}`, pageWidth - 14, 24, { align: 'right' });

                        // Active Filters Details
                        doc.setFontSize(9);
                        doc.setTextColor(100, 100, 100);
                        doc.text(filterText, 14, 45);
                    }

                    // --- PAGE NUMBERS LOGIC ---
                    if (pdfPageNumbers) {
                        doc.setFontSize(9);
                        doc.setTextColor(120, 120, 120);
                        doc.text(
                            `Page ${data.pageNumber}`,
                            pageWidth / 2,
                            pageHeight - 8,
                            { align: 'center' }
                        );
                    }
                },
            });

            doc.save(fileName);
            if (onSuccess) onSuccess();
            onClose();
        } catch (error) {
            console.error("PDF Generation Error", error);
            alert("Failed to generate PDF. Check console for details.");
        } finally {
            setIsExporting(false);
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-zinc-900/60 backdrop-blur-sm p-4 animate-in fade-in duration-200">
            <div className="bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 w-full max-w-md rounded-3xl p-6 sm:p-8 shadow-2xl relative animate-in zoom-in-95 duration-200">
                <button onClick={onClose} className="absolute top-6 right-6 text-zinc-400 hover:text-zinc-900 dark:hover:text-white transition-colors">
                    <X size={20} />
                </button>

                <div className="mb-6">
                    <h3 className="text-xl font-black text-zinc-900 dark:text-white flex items-center gap-2">
                        <Settings className="text-red-600" /> Export PDF Options
                    </h3>
                    <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1">
                        Customize how your report will look.
                    </p>
                </div>

                <div className="space-y-5">

                    {/* Orientation & Size */}
                    <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">Orientation</label>
                            <select
                                value={pdfOrientation}
                                onChange={(e) => setPdfOrientation(e.target.value as 'portrait' | 'landscape')}
                                className="w-full px-3 py-2.5 bg-zinc-50 dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-zinc-700 outline-none text-sm dark:text-white"
                            >
                                <option value="landscape">Landscape</option>
                                <option value="portrait">Portrait</option>
                            </select>
                        </div>
                        <div className="space-y-1.5">
                            <label className="text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">Paper Size</label>
                            <select
                                value={pdfSize}
                                onChange={(e) => setPdfSize(e.target.value as 'a4' | 'letter' | 'legal')}
                                className="w-full px-3 py-2.5 bg-zinc-50 dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-zinc-700 outline-none text-sm dark:text-white"
                            >
                                <option value="a4">A4 Standard</option>
                                <option value="letter">Short (Letter)</option>
                                <option value="legal">Long (Legal)</option>
                            </select>
                        </div>
                    </div>

                    {/* Header Mode */}
                    <div className="space-y-1.5">
                        <label className="text-xs font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">Header Display</label>
                        <select
                            value={pdfHeaderMode}
                            onChange={(e) => setPdfHeaderMode(e.target.value as 'all' | 'first')}
                            className="w-full px-3 py-2.5 bg-zinc-50 dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-zinc-700 outline-none text-sm dark:text-white"
                        >
                            <option value="all">Repeat Header on Every Page</option>
                            <option value="first">Show Header on First Page Only</option>
                        </select>
                    </div>

                    {/* Toggles */}
                    <div className="flex flex-col gap-3 pt-2">
                        <label className="flex items-center gap-3 cursor-pointer">
                            <input type="checkbox" checked={pdfLogo} onChange={(e) => setPdfLogo(e.target.checked)} className="w-4 h-4 accent-red-600 rounded cursor-pointer" />
                            <span className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Include Tugma Logo</span>
                        </label>
                        <label className="flex items-center gap-3 cursor-pointer">
                            <input type="checkbox" checked={pdfPageNumbers} onChange={(e) => setPdfPageNumbers(e.target.checked)} className="w-4 h-4 accent-red-600 rounded cursor-pointer" />
                            <span className="text-sm font-bold text-zinc-700 dark:text-zinc-300">Show Page Numbers</span>
                        </label>
                    </div>

                    {/* Actions */}
                    <div className="flex gap-3 pt-4 border-t border-zinc-100 dark:border-zinc-800">
                        <button
                            onClick={onClose}
                            className="flex-1 py-3 rounded-xl font-bold text-zinc-600 dark:text-zinc-300 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleGeneratePDF}
                            disabled={isExporting}
                            className="flex-1 py-3 rounded-xl font-bold text-white bg-red-600 hover:bg-red-700 transition-colors flex items-center justify-center gap-2 disabled:opacity-50 shadow-lg shadow-red-500/20"
                        >
                            {isExporting ? <Loader2 size={18} className="animate-spin" /> : <FileText size={18} />}
                            Generate
                        </button>
                    </div>

                </div>
            </div>
        </div>
    );
}